---
title: "Why US Needs Immigration"
output: html_document
---

```{r}
library(plyr)
library(dplyr)
library(readstata13)
```

```{r}
#https://data.worldbank.org/
setwd("~/Downloads/political data/")
gdp.data<-read.csv("us japan gdp.csv",stringsAsFactors=F,header=T)
colnames(gdp.data)<-c("year","year.code","country","country.code","gdp.per.capita")
#country comparison
plot(gdp.data$year[gdp.data$country.code=="USA"],gdp.data$gdp.per.capita[gdp.data$country.code=="USA"],
     type="l",lwd=3,col="royalblue2",xlab="Year",
     ylab="Real GDP Per Capita (Current $US)")
lines(gdp.data$year[gdp.data$country.code=="JPN"],gdp.data$gdp.per.capita[gdp.data$country.code=="JPN"],
      lwd=3,col="orange3")
```

```{r}
#https://data.worldbank.org/
country.data<-read.csv("country age demographics.csv",stringsAsFactors=F,header=T)
country.data<-country.data[country.data$Country.Code%in%c("JPN","USA"),]
colnames(country.data)<-c("Year","Year.Code","Country.Name","Country.Code","Age.Dependency.Old",
                         "Fertility.Rate","Net.Migration","Pop.0.14.Total","Pop.15.64.Fraction",
                         "Pop.15.64.Total","Pop.65.Above.Fraction","Pop.65.Above.Total","Pop.Total")
country.data<-country.data[country.data$Year<=as.numeric(format(Sys.Date(),"%Y")),]
par(mfrow=c(1,2))
plot(country.data$Year[country.data$Country.Code=="JPN"],
     country.data$Fertility.Rate[country.data$Country.Code=="JPN"],ylim=c(1,3.5),type="l",lwd=3,
     lty=1,col="orange3",xlab="Year",ylab="Fertility Rate")
lines(country.data$Year[country.data$Country.Code=="USA"],
      country.data$Fertility.Rate[country.data$Country.Code=="USA"],lwd=3,lty=1,col="royalblue2")
country.data$Net.Migration<-as.numeric(country.data$Net.Migration)
plot(country.data$Year[country.data$Country.Code=="JPN"],
     country.data$Net.Migration[country.data$Country.Code=="JPN"],pch=19,col="orange3",
     ylim=c(-2.5*10^5,7*10^6),xlab="Year",ylab="Net Migration")
points(country.data$Year[country.data$Country.Code=="USA"],
       country.data$Net.Migration[country.data$Country.Code=="USA"],pch=19,col="royalblue2")
```

```{r}
#https://cps.ipums.org/cps/
cps.data<-read.csv("cps_00009.csv",stringsAsFactors=F,header=T)
cps.data<-cps.data[cps.data$YEAR>=1994,]
cps.data$FOREIGN.BORN<-ifelse(cps.data$NATIVITY==5,0,1)
cps.data2<-ddply(cps.data,.(YEAR,FOREIGN.BORN),summarize,MEAN.AGE=weighted.mean(AGE,ASECWT))
plot(cps.data2$YEAR[cps.data2$FOREIGN.BORN==0],cps.data2$MEAN.AGE[cps.data2$FOREIGN.BORN==0],type="l",
     ylim=c(30,50),ylab="Average Age (Weighted by Survey Design)",xlab="Year",lwd=3,col="royalblue2")
lines(cps.data2$YEAR[cps.data2$FOREIGN.BORN==1],cps.data2$MEAN.AGE[cps.data2$FOREIGN.BORN==1],type="l",
      col="orange3",lwd=3)
legend("topleft",c("Native","Foreign Born"),lty=c(1,1),col=c("royalblue2","orange3"),lwd=3,bty="n")
```
